### ISSUE TITLE
pipexec doesn't verify of the binary(s) exist

### ISSUE THREAD

**Issue by cyb-r** [flonatel/pipexec#16]
Doing something silly like  `./pipexec -p /var/run/bash.pid -s 5 -- /var/bash` get's no error output even if the binary doesn't exist. 

Doing a simple ps aux seem to lead me to beleave it's not actually running any commands because if I try to run the real bash binary it does the same thing... Yet in this post this project claims it works... [stackexchange](https://unix.stackexchange.com/questions/55751/etc-init-d-script-or-etc-inittab-respawn-on-die)

**Comment by flonatel** [comment]
IMHO here are two things involved:

Syntax error in your command: If you correctly specify the command like `./bin/pipexec -- [ A /tmp/doesnotexists ]` an error is logged: `execv: No such file or directory`

But - and this is a problem - when some rubbish is given, there is no log and even the result is 0 - the rubbish is silently ignored.

**Comment by flonatel** [comment]
Commit https://github.com/flonatel/pipexec/commit/de024080e8dd1d5990392bd217e6b69fec9fa6c9 fixes this.
When now additional parameters are given, an error message is logged.
