### ISSUE TITLE
Diagrams in README do not render readably on github in dark mode

### ISSUE THREAD

**Issue by drawks** [flonatel/pipexec#18]
![Screenshot 2024-03-14 at 7 23 12 AM](https://github.com/flonatel/pipexec/assets/410276/bce011cf-b808-4e58-b22a-c0dbf8506c92)

Black elements on transparent background should probably be rendered with a high contrast (white, maybe?) outline or the transparent background should be replaced with white or something which renders to something viewable.

**Comment by flonatel** [comment]
Thanks for reporting.
