### ISSUE TITLE
Document in readme that package is installable on Debian, Ubuntu, Raspian, Arch

### ISSUE THREAD

**Issue by jlevy** [flonatel/pipexec#6]
This seems like an interesting tool! I came across it from the suggestion at https://github.com/jlevy/the-art-of-command-line/issues/244

Are there any plans to make packages available for more common distros like Ubuntu and Red Hat as well? It's a bit specialized, but since it does something few other commands do, I'd be willing to include it if it in https://github.com/jlevy/the-art-of-command-line if it were readily installable on most Linuxes.

Also, a section in your readme discussing what other alternatives, if any, there are, would be helpful.

**Comment by flonatel** [comment]
Thanks for the comment :-)

Currently I know about the following distros that include pipexec:
* Debian: https://packages.debian.org/sid/pipexec (all architectures supported: including e.g. arm)
* Ubuntu: http://packages.ubuntu.com/wily/pipexec
* ArchLinux: https://aur.archlinux.org/packages/pipexec-git
* Raspian: http://mirror.ancl.hawaii.edu/linux/raspian/raspbian/pool/main/p/pipexec

I personally use Debian - therefore this had priority for me; and I'm very happy that I found a very good maintainer for Debian (Thorsten).

Currently I have no idea how to include a package in the Fedora / Centos / Redhat universe. I'm pretty sure for Redhat that *they* chose their packages (and they really do not have that many).  Until now there was just no need - you are the first person asking for other distributions.

I'll think about it and also about your hint for the readme.

Kind regards - Andre

**Comment by jlevy** [comment]
Ah, good to know! Personally, just wanted to know it's available on the main distros. I suggest you put exactly this info in the readme, as based on the current readme only mentioning Arch, I'd erroneously assumed it wasn't packaged for Ubuntu, which is what I usually use. :)

**Comment by jlevy** [comment]
I'll consider adding it to TAOCL once I've had a chance to try it and have some examples of concrete use cases (suggestions welcome).

**Comment by flonatel** [comment]
Updated readme with distros that are known to ship pipexec.
